variables:
  APP_VERSION: "1.1"
stages:
- build
- integrate
- deploy



build_sb_commands:
  stage: build
  image: java:8-jdk
  cache:
    paths:
    - .gradle/wrapper
    - .gradle/caches
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
  - ./gradlew test
  - ./gradlew clean shadowJar
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 day


integrate_sb_commands:
  stage: integrate
  image: sschuepbach/metafacture-runner:latest
  before_script:
  - mkdir e2e
  - cp -r .e2e/baseLineResource e2e
  script:
  - cp build/libs/swissbibMF-plugins-$APP_VERSION-all.jar /app/plugins
  - cd e2e/baseLineResource
  - bash /app/flux.sh resource.flux
  - diff -q *.jsonld
  artifacts:
    paths:
    - /app
    expire_in: 1 day

deploy_to_docker_hub:
  stage: deploy
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  - docker push "$CI_REGISTRY_IMAGE"
# only:
# - master
