variables:
  APP_VERSION: "1.1"
stages:
- build
- integrate
# - test
# - deploy



build_sb_commands:
  stage: build
  image: java:8-jdk
  cache:
    paths:
    - .gradle/wrapper
    - .gradle/caches
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
  - ./gradlew shadowJar
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 week


integrate_sb_commands:
  stage: integrate
  image: archlinux/base:latest
  before_script:
  - pacman -Syy
  - pacman -S --noconfirm wget
  script:
  - wget https://github.com/metafacture/metafacture-core/releases/download/metafacture-core-5.0.0/metafacture-core-5.0.0-dist.tar.gz
  - tar xzf metafacture-core-5.0.0-dist.tar.gz
  - cp swissbibMF-plugins-$APP_VERSION-all.jar metafacture-core-5.0.0-dist/plugins

# e2e_tests:
#   stage: test

# deploy_to_docker_hub:
#   image: 
#   only:
#   - master
