variables:
  APP_VERSION: "1.1"
stages:
- build
- integrate
- deploy



build_sb_commands:
  stage: build
  image: java:8-jdk
  cache:
    paths:
    - .gradle/wrapper
    - .gradle/caches
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
  - ./gradlew integrationTest shadowJar
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 day


integrate_sb_commands:
  stage: integrate
  image: archlinux/base:latest
  before_script:
  - pacman -Syy
  - pacman -S --noconfirm wget tar grep jre8-openjdk-headless diff
  - mkdir e2e
  - cp -r .e2e/baseLineResource e2e
  script:
  - wget https://github.com/metafacture/metafacture-core/releases/download/metafacture-core-5.0.0/metafacture-core-5.0.0-dist.tar.gz
  - tar xzf metafacture-core-5.0.0-dist.tar.gz
  - cp build/libs/swissbibMF-plugins-$APP_VERSION-all.jar metafacture-core-5.0.0-dist/plugins
  - cd e2e/baseLineResource
  - bash ../../metafacture-core-5.0.0-dist/flux.sh resource.flux
  - diff -q *.jsonld
  after_script:
  - rm -r e2e
  artifacts:
    paths:
    - metafacture-core-5.0.0-dist
    expire_in: 1 day

deploy_to_docker_hub:
  stage: deploy
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  - docker push "$CI_REGISTRY_IMAGE"
# only:
# - master
